language: python
python:
    - "2.7"
env: PGVERSION=9.2
dist: trusty
sudo: required
cache: pip
before_install:
    - chmod +x ./bin/travis-build.bash
    - chmod +x ./bin/travis-run.sh
install:
    # - ./bin/travis-build.bash
    # Installing CKAN errors out; skip for now
    - pip install flake8
    - pip install coveralls
script:
    # - ./bin/travis-run.sh
    # Installing CKAN errors out; skip for now
    - flake8
after_success:
    - coveralls
