language: python
python:
    - "2.7"
env: PGVERSION=9.2
dist: trusty
sudo: required
cache: pip
env:
    - CKANVERSION=2.7
services:
    - postgresql
install:
    - bash bin/travis-build.bash
    - pip install flake8
script:
    - sh bin/travis-run.sh
    - flake8 ./ckanext-kpis